# -*- coding: utf-8 -*-
"""Project -1 (langchain)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BkwDIW3G10FrIiY-AMAk3BCuhZrBJaA
"""

!pip install langchain_community langchain_core langchain_groq chromadb langchain_huggingface

from langchain_core.documents import Document
docs = [
    Document(page_content="RAG (Retrieval-Augmented Generation) combines a retriever with a generator, fetching relevant context before the LLM produces an answer."),
    Document(page_content="A typical RAG pipeline has three stages: indexing, retrieval, and generation."),
    Document(page_content="Indexing involves splitting documents into chunks, embedding each chunk, and storing the vectors in a vector database."),
    Document(page_content="Chunk size and overlap directly affect retrieval quality; chunks too large dilute relevance, chunks too small lose context."),
    Document(page_content="Embeddings are dense numerical vectors that represent the semantic meaning of text, allowing similarity comparison via distance metrics."),
    Document(page_content="Bi-encoders embed queries and documents separately into a shared vector space, enabling fast retrieval at scale."),
    Document(page_content="Cross-encoders jointly process a query and document pair, producing more accurate relevance scores but at higher compute cost."),
    Document(page_content="A common RAG pattern uses a bi-encoder for fast initial retrieval, then a cross-encoder to rerank the top candidates."),
    Document(page_content="Cosine similarity measures the angle between two vectors and is the most common metric for comparing embeddings in RAG retrieval."),
    Document(page_content="Vector normalization scales embeddings to unit length, making cosine similarity and dot product equivalent for ranking."),
    Document(page_content="MMR (Maximal Marginal Relevance) selects retrieved chunks that are both relevant to the query and diverse from each other."),
    Document(page_content="Hybrid search combines sparse retrieval like BM25 with dense vector search, merging results to capture both keyword and semantic matches."),
    Document(page_content="BM25 is a sparse, term-frequency-based retrieval algorithm that works well for exact keyword matches but misses semantic similarity."),
    Document(page_content="Reciprocal rank fusion is a technique for merging ranked result lists from multiple retrievers, such as BM25 and dense search."),
    Document(page_content="Reranking applies a more expensive model, often a cross-encoder, to reorder an initial set of retrieved candidates by finer relevance."),
    Document(page_content="Context window limits how much retrieved text can be passed to the LLM, which is why retrieval must prioritize the most relevant chunks."),
    Document(page_content="Retrieval failure modes include returning irrelevant chunks, missing relevant chunks, or retrieving redundant near-duplicate chunks."),
    Document(page_content="Query rewriting or expansion reformulates the user's question before retrieval to improve match quality against the indexed documents."),
    Document(page_content="Self-querying retrievers let an LLM generate structured filters from a natural language query to narrow a vector search."),
    Document(page_content="Evaluating RAG systems typically measures retrieval metrics like recall and precision alongside generation metrics like faithfulness and relevance."),
    Document(page_content="Recursive character text splitting breaks documents along a hierarchy of separators like paragraphs, sentences, then words, to preserve structure."),
    Document(page_content="Semantic chunking splits text based on shifts in meaning between sentences rather than fixed character counts."),
    Document(page_content="Parent-child retrieval indexes small chunks for precise matching but returns the larger parent chunk to give the LLM more context."),
    Document(page_content="Metadata filtering restricts vector search to a subset of documents, such as by date, source, or category, before similarity ranking runs."),
    Document(page_content="Grounding refers to ensuring the LLM's generated answer is supported by the retrieved context rather than the model's parametric knowledge."),
    Document(page_content="Hallucination in RAG occurs when the generated answer contradicts or goes beyond what the retrieved documents actually support."),
    Document(page_content="Citation or source attribution in RAG means the generated answer references which retrieved chunk supports each claim."),
    Document(page_content="Multi-hop retrieval performs multiple rounds of retrieval and reasoning to answer questions that require combining information from several documents."),
    Document(page_content="HyDE (Hypothetical Document Embeddings) generates a hypothetical answer first, then embeds it to retrieve documents similar to that hypothetical answer."),
    Document(page_content="Chunk overlap preserves context across chunk boundaries by repeating a small portion of text at the end of one chunk and start of the next."),
]

from langchain_core import vectorstores
from prompt_toolkit.layout.processors import HighlightIncrementalSearchProcessor
import os
import requests
from google.colab import userdata
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage
from langchain_core.tools import tool
from langchain_core.runnables import RunnableLambda, RunnablePassthrough, RunnableParallel
from langchain_community.vectorstores import Chroma
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_groq import ChatGroq
from langchain_core.output_parsers import  StrOutputParser
from langchain_huggingface import HuggingFaceEmbeddings

GROQ_API_KEY = userdata.get('GROQ_API_KEY')

llm = ChatGroq(
    model = "openai/gpt-oss-120b",
    api_key = GROQ_API_KEY
)

@tool
def get_weather(city: str) -> str:
  """Get the weather of current given city.
  use when user asked about weather conditions"""
  url = f"https://wttr.in/{city}?format=3"
  response = requests.get(url)
  return response.text

@tool
def calculate(expression:str) -> str:
  """Evaluate a mathematical expression safely.
    Use when the user wants to compute numbers."""
  try:
    result = eval(expression, {"__builtins__": {}}, {})
    return f"Result: {result}"
  except Exception as e:
    return f"Error:{e}"

store = {}

def get_session_history(session_id):
  if session_id not in store:
    store[session_id] = ChatMessageHistory()
  return store[session_id]

embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-m3")

vectorstores = Chroma.from_documents(
    docs,
    embedding = embeddings
)

retriever = vectorstores.as_retriever(
    search_type = "mmr",
    search_kwargs = {
        "fetch_k":6,
        "k": 3,
        "lambda_mult":0.7
    }
)

def format_docs(doc):
  return ''.join([d.page_content for d in doc])

tools = [get_weather, calculate]
llm_with_tools = llm.bind_tools(tools)
tool_map = {t.name: t for t in tools}

def run_with_tools(user_input: str, history : list) -> str:
  messages = history + [HumanMessage(content=user_input)]
  response =  llm_with_tools.invoke(messages)

  if response.tool_calls:
    messages.append(response)
    for tc in response.tool_calls:
      result = tool_map[tc["name"]].invoke(tc["args"])
      messages.append(
          ToolMessage(content= str(result),
          tool_call_id = tc["id"]
      ))
      final = llm_with_tools.invoke(messages)
      print(final.content)      # <-- added this line
      return final.content
  print(response.content)       # <-- added this line
  return response.content

def run_rag(user_input: str , history: list) -> str:
  context = format_docs(retriever.invoke(user_input))
  prompt = ChatPromptTemplate.from_messages([
      ("system", "Answer the question Only using {context}"),
      MessagesPlaceholder(variable_name='history'),
      ("human", "{input}")
  ])
  response = prompt | llm | StrOutputParser()
  result = ""
  for chunk in response.stream({"context":context, "input":user_input, "history":history}):
    print(chunk, end ="", flush = True)
    result += chunk
  return result


def run_general(user_input: str , history: list) -> str:
  prompt = ChatPromptTemplate.from_messages([
      ("system", "You're an Helpful Assistant, Answer the question"),
      MessagesPlaceholder(variable_name='history'),
      ("human", "{input}")
  ])
  response = prompt | llm | StrOutputParser()
  result = ""
  for chunk in response.stream({"input":user_input,"history":history}):
    print(chunk, end ="", flush = True)
    result += chunk
  return result


intent_classififer = ChatPromptTemplate.from_template(
    """Classify into ONE Category word from question
    -weather ( when user asked about weather conditions)
    -calculate(when user asked to compute expression)
    -rag(when user asked about Rag)
    -general(anything)

    Question: {input}
    respond with ONLY ONE Category word.
    """
)

Classifer = intent_classififer | llm | StrOutputParser()

def route(info):
  intent =  info["intent"].strip().lower()

  if "weather" in intent or "calculate" in intent:
    return run_with_tools(info['input'], info['history'])
  elif "rag" in intent:
    return run_rag(info['input'], info['history'])
  else :
    return run_general(info['input'], info['history'])

def chat(user_input: str, session_id: str) -> str:
  history_obj = get_session_history(session_id)
  history = history_obj.messages
  intent = Classifer.invoke({"input":user_input})
  response = route({"intent": intent,"input":user_input, "history":history})
  history_obj.add_messages([HumanMessage(content=user_input)])
  history_obj.add_messages([AIMessage(content=response)])
  return response

while True:
  user_input = input("Ask Anything(Weather or Calculate or General): ")
  if user_input == "exit":
    break
  chat(user_input, session_id="yogi")
  print()

